import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import Navbar from './components/layout/Navbar';
import { ReducerProvider } from '../store';

export const metadata: Metadata = {
	title: 'Welcome to Dev-Social',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<Script
					src='https://kit.fontawesome.com/aca412044b.js'
					strategy='afterInteractive'
				></Script>
			</head>
			<body className=' body'>
				<ReducerProvider>
					<Navbar />
					{children}
				</ReducerProvider>
			</body>
		</html>
	);
}
